### ISSUE TITLE
Bug: package.json file may be lacking a valid "main" entry

### ISSUE THREAD

**Issue by Skipper-kenya** [Renji-and-frens/meal-planner-frontend#15]
### The error captured below is expirienced after running ```npm install and npm start```

```bash
Error: Cannot find module '\node_modules\isexe\index.js'.
 Please verify that the package.json has a valid "main" entry
```

**Comment by yuuni-mikawane** [comment]
Thanks @Skipper-kenya for letting us know, we'll investigate soon. Much appreciated.
By the way, due to the team being relatively new, the project not being stabilized yet, and other reasons, we are not set on accepting external code contributions yet. Really sorry about this. We are still discussing about this.

**Comment by Skipper-kenya** [comment]
Noted. Remember  to tag me on contributions once you are set.  Sounds like a cool project and I'd  like to help

**Comment by RenijS** [comment]
Fix: https://stackoverflow.com/questions/9023672/how-do-i-resolve-cannot-find-module-error-using-node-js

<img width="755" alt="Screenshot 2024-04-23 at 3 51 40 pm" src="https://github.com/Renji-and-frens/meal-planner-frontend/assets/69236889/0b4acc79-8d98-4b98-b029-74ee0f827e52">

**Comment by Skipper-kenya** [comment]
thanks for sharing
